### ISSUE TITLE
Due Date

### ISSUE THREAD

**Issue by LaFrish** [socialtables/drawing-app-challenge#2]
Hi,
Is there a due date for this challenge?

Thank you in advance!

**Comment by elifitch** [comment]
@LaFrish I'm so sorry we missed this!  The due date was actually last night, however if you're still interested and you have time to get in a submission before Friday, we'll happily consider you for the position.

**Comment by LaFrish** [comment]
@elifitch Definitely still interested. I will finish up and send it over as soon as I can. Thank you for the update!

**Comment by elifitch** [comment]
@LaFrish Fantastic!
