### ISSUE TITLE
Social Tables Logo Missing from Repo?

### ISSUE THREAD

**Issue by christianhoward** [socialtables/drawing-app-challenge#5]
In the design.png file, it looks like there is a Social Tables logo in the Image Stamp section of the sidebar. I've looked through the repo and haven't been able to find that image file. Is this something I should create on my own?

Also, it looks like gmail does not allow users to send .js files, even in zip format. Any recommendations on how to provide the submission?

Thanks!

**Comment by timfoley** [comment]
Good catch on both accounts! 

I've added an [icon](https://github.com/socialtables/drawing-app-challenge/blob/master/public/img/st-icon-1.png) to repo in the `public/img/` folder. 

We've also updated the submission instructions to take into account gmail's latest attachment policy. You can now upload your materials to your favorite cloud host (Dropbox, Google Drive, etc.) and send us the link. 

Thanks for reaching out; have fun with the challenge!

**Comment by christianhoward** [comment]
@timfoley Thanks for the update. I appreciate it!
